function contourimg
global I1 a1 longueur pop edgeseuil edgesigma sigmatext kI1
global radiodefaut radiohoriz radiovertic directions contourappbut seuiltext
%IF image binaire --> IMPOSSIBLE
figure('name','Contour','position',[400 250 500 300]...
            ,'color',[1 1 1],'menubar','none','resize','off');

subplot(122),imshow(I1)

uicontrol('style','text','position',[290 250 150 20],'string',['* ',a1,' *']...
    ,'backgroundcolor',[1 1 1],'fontsize',12);

pop=uicontrol('style','popup','position',[30 180 150 30],'string'...
    ,'Sobel|Prewitt|Roberts|Log|Canny|gradient morphologique|laplacien'...
    ,'backgroundcolor',[1 .9 .7],'fontsize',10,'fontweight','bold','callback','contourpop');

edgeseuil=uicontrol('style','edit','position',[310 160 70 25],'foregroundcolor',[.5 .4 .2]...
    ,'backgroundcolor',[1 1 .8],'fontname','arial black','fontsize',10,...
    'tooltipstring','entrez le seuil du contour','string','10');
edgesigma=uicontrol('style','edit','position',[310 120 70 25],'foregroundcolor',[.5 .4 .2]...
    ,'backgroundcolor',[1 1 .8],'fontname','arial black','fontsize',10,...
    'tooltipstring','entrez la valeur de Sigma','visible','off','string','2');
seuiltext=uicontrol('style','text','position',[205 150 100 30],'string','         Seuil  :'...
    ,'foregroundcolor',[1 .8 .6],'fontname','tahoma','fontsize',12,'backgroundcolor',[.5 .5 .5]);
sigmatext=uicontrol('style','text','position',[205 110 100 30],'string','        Sigma :'...
    ,'foregroundcolor',[1 .8 .6],'fontname','tahoma','fontsize',12,'backgroundcolor',[.5 .5 .5]...
    ,'visible','off');
directions=uibuttongroup('units','pixels','position',[30 60 150 100]...
    ,'backgroundcolor',[.5 .5 .5],'title','Directions :','foregroundcolor',[1 .8 .2]...
    ,'fontsize',10,'highlightcolor',[1 .8 .2]...
    ,'shadowcolor',[1 .8 .2]);
radiodefaut=uicontrol('style','radio','parent',directions,'position',[10 60 130 20]...
    ,'string','par defaut','foregroundcolor',[1 .8 .3],'fontname','arial black'...
    ,'fontsize',10,'backgroundcolor',[.5 .5 .5]);
radiohoriz=uicontrol('style','radio','parent',directions,'position',[10 35 130 20]...
    ,'string','horizontal','foregroundcolor',[1 .8 .3],'fontname','arial black'...
    ,'fontsize',10,'backgroundcolor',[.5 .5 .5]);
radiovertic=uicontrol('style','radio','parent',directions,'position',[10 10 130 20]...
    ,'string','vertical','foregroundcolor',[1 .8 .3],'fontname','arial black'...
    ,'fontsize',10,'backgroundcolor',[.5 .5 .5]);
contourappbut=uicontrol('position',[180 10 80 30],'CData',imread('systeme\appliq.jpg')...
        ,'string','appliquer','fontname','arial black','fontsize',10,...
        'foregroundcolor',[0 0.5 0],'callback','contourimgappliq','userdata',0);

uicontrol('position',[360 10 80 30],'CData',imread('systeme\d2.jpg')...
            ,'string','annuler','fontname','arial black','fontsize',10,'foregroundcolor'...
            ,[0.5 .4 .2],'callback','close');
uicontrol('position',[270 10 80 30],'CData',imread('systeme\d2.jpg')...
    ,'string','OK','fontname','arial black','fontsize',10,'foregroundcolor'...
    ,[0.5 .4 .2],'callback','contourimgOK');