function nivcontour
global nivcont I1 f_n a1
% *********************** FIGURE ***************************
f_n=figure('name','niveaux du contour','position',[400 250 600 350]...
    ,'color',[1 1 1],'menubar','none','resize','off');

% *********************** AFFICHER L'IMAGE ***************************
subplot(122), imshow(I1); title(a1,'color',[0 0 0],'Fontangle','Italic')

% *********************** NIVEAUX DE CONTOUR ***************************
uicontrol('style','text','position',[70 220 200 30]...
                    ,'backgroundcolor',[1 1 1],'foregroundcolor'...
                    ,[0 0 0],'visible','on','string',...
  'Entrez le nombre de niveaux du contour :'...
  ,'fontangle','italic','fontsize',10,'FontWeight','bold');  

% Valeur 1
nivcont=uicontrol('style','edit','position',[135 180 70 20]...
    ,'string','3','fontsize',10);

% *********************** BOUTONS ***************************
% Bouton de visualisation
uicontrol('style','push',...
                'position',[130 115 80 30],...
                'string','Visualiser',...
                'FontSize',8,'Fontangle','Italic','FontWeight','bold',...
                'callback','nivcontourappliq');
% Bouton annuler
uicontrol('style','push',...
                'position',[200 60 80 30],...
                'string','Annuler',...
                'FontSize',8,'Fontangle','Italic','FontWeight','bold',...
                'callback','close');
% Bouton ok            
uicontrol('style','push',...
                'position',[60 60 80 30],...
                'string','OK',...
                'FontSize',8,'Fontangle','Italic','FontWeight','bold',...
                'callback','nivcontourOK');


%Faire un if pour l'image binaire, I=image binaire --> impossible à faire
%un contour