function op3dsagittal
global longueur hauteur nombrsagit nombrsag rotat3d
figure('name','coupes sagittales','menubar','none','resize','off'...
    ,'color',[.5 .5 .5]);
nombrsag=uicontrol('style','edit','position',[longueur/1.7066-85 hauteur/1.536-25 70 25]...
    ,'backgroundcolor',[1 1 .8],'fontname','arial black','fontsize',12,...
    'foregroundcolor',[.6 .4 .4]);

load mri
D = squeeze(D);
D(:,1:nombrsagit,:) = [];
p1 = patch(isosurface(D, 5),'FaceColor',[1 .74 .65],...
     'EdgeColor','none');
p2 = patch(isocaps(D, 5),'FaceColor','interp',...
    'EdgeColor','none');
view(3); axis tight; daspect([1,1,.4])
colormap(gray(100))
camlight left; camlight; lighting gouraud
isonormals(D,p1)

set(gcf,'renderer','opengl','color',[.5 .5 .5],'menubar','none'...
    ,'position',[longueur/2.8444 hauteur/7.68 longueur/1.7066 hauteur/1.536],'resize','off')
rotat3d=uicontrol('position',[1 hauteur/1.6695 100 40],'string','Vue 3D        ','fontname','arial black'...
    ,'fontsize',10,'foregroundcolor',[0 .4 0],'cdata',imread('systeme\rotatoff.jpg')...
    ,'callback','op3drot','userdata',0);

uicontrol('position',[longueur/1.7066-100 hauteur/1.536-55 100 30],'string','appliquer'...
    ,'cdata',imread('systeme\h3.jpg'),'fontname','arial black','fontsize',12,...
    'foregroundcolor',[.6 .2 .2],'callback','op3dsagittalappliq');
