function QuitterDialog
figure('name','Quitter','menubar','none','position',[450 300 400 200]...
    ,'color',[1 1 1],'resize','off');

uicontrol('style','text','position',[50 80 300 50],'string'...
    ,'Voulez-vous vraiment quitter?','backgroundcolor',[1 1 1]...
    ,'fontsize',12,'Fontangle','Italic','fontweight','bold');
uicontrol('position',[230 40 80 30],'string','Non'...
    ,'fontsize',12,'fontangle','italic','fontweight','bold','callback','close');
uicontrol('position',[95 40 80 30],'string','Oui '...
    ,'fontsize',12,'fontangle','italic','fontweight','bold','callback','close all');

