function rotation2
global longueur I1 mI1s nI1s a1 rotatangleedit2 imrot2 rotatt12 rotatt22 hor ver no kI1
imrot2=I1;
[mI1 nI1 kI1]=size(I1);
mI1s=num2str(mI1); nI1s=num2str(nI1);
% *********************** FIGURE ***************************
figure('name','Rotation','position',[longueur/2.2755 150 406 500]...
            ,'color',[1 1 1],'menubar','none','resize','off');

% *********************** AFFICHAGE ***************************
%subplot(222),imshow(I1)
axes('units','pixels','position',[90 50 250 200]); imshow(I1)

title(a1,'color',[0 0 0],'Fontangle','Italic')

% *********************** EFFET MIROIR ***************************
miroir=uibuttongroup('units','pixels','position',[30 350 150 120],'title','Effet miroir :'...
    ,'backgroundcolor',[1 1 1],'fontsize',10,...
    'highlightcolor',[.63 .63 .63],'fontangle','italic');
% Aucun
no=uicontrol('style','radio','parent',miroir,'position',[30 70 100 30]...
    ,'string','aucun','fontsize',10,...
    'backgroundcolor',[1 1 1]);
% Horizontal
hor=uicontrol('style','radio','parent',miroir,'position',[30 40 100 30]...
    ,'string','horizontal','fontsize',10,...
    'backgroundcolor',[1 1 1]);
% Vertical
ver=uicontrol('style','radio','parent',miroir,'position',[30 10 100 30]...
    ,'string','vertical','fontsize',10,...
    'backgroundcolor',[1 1 1]);

% *********************** ROTATION ***************************
rotatt=uibuttongroup('units','pixels','position',[230 350 150 120],'title','Rotation :'...
    ,'backgroundcolor',[1 1 1],'fontsize',10,...
    'highlightcolor',[.63 .63 .63],'fontangle','italic');
% Entière
rotatt12=uicontrol('style','radio','parent',rotatt,'position',[10 70 130 30]...
    ,'string','image entière','fontsize',10,...
    'backgroundcolor',[1 1 1]);
% Originale
rotatt22=uicontrol('style','radio','parent',rotatt,'position',[10 40 130 30]...
    ,'string','taille originale','fontsize',10,...
    'backgroundcolor',[1 1 1]);
% Angle
uicontrol('style','text','parent',rotatt,'position',[5 1 70 30],'string','angle :','fontsize',10,...
    'backgroundcolor',[1 1 1],'fontangle','italic');
% Valeur
rotatangleedit2=uicontrol('style','edit','parent',rotatt,'position',[70 13 60 20],'backgroundcolor',[1 1 1],...
    'fontsize',10,'string','0');

% *********************** BOUTONS ***************************
% Bouton de visualisation
uicontrol('position',[65 300 80 30],'string','Visualiser',...
    'fontsize',8,'fontangle','italic','fontweight','bold','callback','rotationappliq2');
% Bouton ok        
uicontrol('position',[165 300 80 30],'string','OK',...
    'fontsize',8,'fontangle','italic','fontweight','bold','callback','rotationOK2');
% Bouton annuler
uicontrol('position',[265 300 80 30],'string','Annuler',...
    'fontsize',8,'fontangle','italic','fontweight','bold','callback','close');