function taille
global rapp lon_lar
% ***************************** FIGURE ********************************
figure('name','Taille de l''image','resize','off'...
    ,'position',[500 300 300 200],'menubar','none','color',[1 1 1]);


% ********************** CHOIX DE REDIMENSIONNEMENT ***********************
% Titre
tai=uibuttongroup('units','pixels','position',[45 70 200 100],'title','Redimensionner :'...
    ,'backgroundcolor',[1 1 1],'fontsize',10,...
    'highlightcolor',[.63 .63 .63],'fontangle','italic');
% Choix 1
rapp=uicontrol('style','radio','parent',tai,'position',[10 40 170 30]...
    ,'string','avec un facteur d''échelle','fontsize',10,...
    'backgroundcolor',[1 1 1]);
% Choix 2
lon_lar=uicontrol('style','radio','parent',tai,'position',[10 10 170 30]...
    ,'string','largeur x hauteur','fontsize',10,...
    'backgroundcolor',[1 1 1]);

% ******************************* BOUTONS ********************************
% Bouton ok
uicontrol('position',[50 20 80 30],'string','OK','FontSize',8,'Fontangle','Italic',...
    'FontWeight','bold','callback','tail');
% Bouton annuler
uicontrol('position',[160 20 80 30],'string','Annuler','FontSize',8,'Fontangle','Italic',...
    'FontWeight','bold','callback','close');